{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atrosha.fullname" . }}-secrets
  labels:
    {{- include "atrosha.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.permitSecretKey }}: "CHANGE-ME-IN-PRODUCTION"
  {{ .Values.secrets.clickhousePasswordKey }}: ""
{{- end }}
