"use server";

import { createClient } from "@/lib/supabase-server";
import { revalidatePath } from "next/cache";
import nacl from "tweetnacl";

const toHex = (arr: Uint8Array) => Array.from(arr).map(b => b.toString(16).padStart(2, '0')).join('');

export async function createAgent(name: string, limit: number) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) return { error: "Unauthorized: User session missing" };

        let orgId = user.user_metadata?.org_id;

        // Fallback: If metadata is missing org_id, fetch the first available organization
        if (!orgId) {
            const { data: orgs } = await supabase.from('organizations').select('id').limit(1);
            if (orgs && orgs.length > 0) {
                orgId = orgs[0].id;
            } else {
                return { error: "No organization found in database. Please complete onboarding first." };
            }
        }

        // Generate Ed25519 Keypair using TweetNaCl for guaranteed Node/Edge support
        const keyPair = nacl.sign.keyPair();
        const pubHex = toHex(keyPair.publicKey);
        // tweetnacl returns 64-byte secretKey (first 32 bytes are the seed/private key proper for Ed25519)
        const privHex = toHex(keyPair.secretKey.slice(0, 32));

        // 1. Save to Supabase (for the Dashboard UI)
        const { data, error } = await supabase.from('agents').insert({
            name,
            organization_id: orgId,
            pubkey: pubHex,
            daily_limit_cents: limit,
            is_active: true
        }).select().single();

        if (error) {
            return { error: `Database error: ${error.message}` };
        }

        // 2. Synchronize with the Live Rust Proxy (for Redis / Execution)
        // Add a 4s timeout so it doesn't crash Vercel (10s limit) if Render proxy is sleeping
        const proxyUrl = process.env.NEXT_PUBLIC_PROXY_URL || "https://atrosha.onrender.com";
        const adminSecret = process.env.ADMIN_SECRET || "admin-secret-change-me"; // Note: Use real env var in prod

        try {
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), 4000);

            const syncRes = await fetch(`${proxyUrl}/admin/agents`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-Atrosha-Admin-Secret": adminSecret,
                    "X-Atrosha-Org-ID": orgId
                },
                body: JSON.stringify({
                    agent_id: data.id, // The UUID generated by Supabase
                    pub_hex: pubHex,
                    role: "General Purpose"
                }),
                signal: controller.signal
            });

            clearTimeout(timeoutId);

            if (!syncRes.ok) {
                console.error("Failed to sync agent to Proxy", await syncRes.text());
            }
        } catch (syncErr: unknown) {
            console.warn("Network error or timeout syncing to proxy (sleeping Render). Agent created in DB.", syncErr instanceof Error ? syncErr.message : String(syncErr));
        }

        revalidatePath("/agents");

        // We only return the private key once. It is never stored in our DB.
        // JSON parse/stringify ensures we don't return complex objects across the Server Action boundary
        const plainData = JSON.parse(JSON.stringify(data));
        return { data: { ...plainData, _privateKey: privHex } };
    } catch (err: unknown) {
        return { error: `Server crash: ${err instanceof Error ? err.message : String(err)}` };
    }
}
