import torch
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn
import time

class AdversarialDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=512):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer.encode(self.texts[idx])
        ids = enc.ids[:self.max_len]
        
        pad_len = self.max_len - len(ids)
        input_ids = ids + [0] * pad_len
        attention_mask = [1] * len(ids) + [0] * pad_len
        
        return {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
            "label": torch.tensor(self.labels[idx], dtype=torch.long),
        }

class BlueTeamUpdater:
    """
    Blue Team AI: Performs continuous fine-tuning ("immune response") on the semantic engine
    using the bypass payloads generated by the Red Team.
    """
    def __init__(self, model, tokenizer, device="cuda" if torch.cuda.is_available() else "cpu"):
        self.model = model
        self.device = device
        self.tokenizer = tokenizer
        self.optimizer = torch.optim.AdamW(self.model.parameters(), lr=1e-5, weight_decay=0.01)
        self.loss_fn = nn.CrossEntropyLoss()
        
    def train_on_bypasses(self, adv_texts, true_label_id, epochs=2, batch_size=16):
        """
        Takes a list of adversarial texts that bypassed the model, applies the correct true label,
        and fine-tunes the model to recognize them. By giving a low LR, we avoid catastrophic forgetting
        while patching the vulnerability.
        """
        if not adv_texts:
            return 0.0

        ds = AdversarialDataset(adv_texts, [true_label_id] * len(adv_texts), self.tokenizer)
        loader = DataLoader(ds, batch_size=batch_size, shuffle=True)
        
        self.model.train()
        total_loss = 0.0
        
        for epoch in range(epochs):
            for batch in loader:
                ids = batch["input_ids"].to(self.device)
                mask = batch["attention_mask"].to(self.device)
                labels = batch["label"].to(self.device)
                
                self.optimizer.zero_grad()
                
                logits = self.model(input_ids=ids, attention_mask=mask)
                loss = self.loss_fn(logits, labels)
                
                loss.backward()
                torch.nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)
                self.optimizer.step()
                
                total_loss += loss.item()
                
        return total_loss / (epochs * max(1, len(loader)))
